### ISSUE TITLE
Input Graph Format

### ISSUE THREAD

**Issue by mabdullahsoyturk** [groute/groute#10]
Hi,

I can run, for example, PageRank with a randomly generated graph (by using --gen-graph) but I cannot run it with a real graph (Full USA) that I gathered from [DIMACS Challenge Website](http://www.diag.uniroma1.it/challenge9/download.shtml). 

Here is the error when I run ./pr --graphfile=USA-road-d.USA.gr: 
Unknown file version

Since --ggr is true by default and the input file I provide is a gr file (USA-road-d.USA.gr), I was expecting it to run without a problem. Can you provide an example input file that I can download?

Best,
Muhammet

**Comment by tbennun** [comment]
Hi Muhammet,

I'm not sure what's causing this issue, but we have detailed instructions on how to download the .gr files we used for the paper (which includes USA full) in the following repo: https://github.com/groute/ppopp17-artifact

Please let me know if this works!

**Comment by mabdullahsoyturk** [comment]
Awesome. I was not aware of that repository. I will try and come back to you.

**Comment by mabdullahsoyturk** [comment]
I was able to run bfs with USA road input that I gathered using **dataset/download.sh** in [https://github.com/groute/ppopp17-artifact](https://github.com/groute/ppopp17-artifact). Thanks for the help.

**Comment by the-humble-programmer** [comment]
> Hi,
> 
> I can run, for example, PageRank with a randomly generated graph (by using --gen-graph) but I cannot run it with a real graph (Full USA) that I gathered from [DIMACS Challenge Website](http://www.diag.uniroma1.it/challenge9/download.shtml).
> 
> Here is the error when I run ./pr --graphfile=USA-road-d.USA.gr: Unknown file version
> 
> Since --ggr is true by default and the input file I provide is a gr file (USA-road-d.USA.gr), I was expecting it to run without a problem. Can you provide an example input file that I can download?
> 
> Best, Muhammet

I have exactly the same issue. I would like to run, for example, CC on my own example .gr file. But when I do so, with the same command shown above, I get the same error: Unknown file version. How do I get it to run on my own .gr files?

Thanks!

**Comment by tbennun** [comment]
Again, I have no idea why this is happening, but according to the [code](https://github.com/groute/groute/blob/master/src/utils/parser.cpp#L412) it looks like a malformed header. How are you creating your .gr files?

**Comment by the-humble-programmer** [comment]
> Again, I have no idea why this is happening, but according to the [code](https://github.com/groute/groute/blob/master/src/utils/parser.cpp#L412) it looks like a malformed header. How are you creating your .gr files?

I have used Gunrock's tool for converting a .mtx file to a .gr file (this is the link: https://github.com/gunrock/gunrock/tree/master/tools)
For example, this is a sample .gr file so generated:

```
p sp 33 46
a 3 1 1
a 3 2 1
a 1 3 1
a 2 3 1
a 4 3 1
a 3 4 1
a 5 4 1
a 9 4 1
a 4 5 1
a 6 5 1
a 14 5 1
a 5 6 1
a 9 7 1
a 9 8 1
a 4 9 1
a 7 9 1
a 8 9 1
a 10 9 1
a 9 10 1
a 11 10 1
a 10 11 1
a 12 11 1
a 13 11 1
a 11 12 1
a 11 13 1
a 14 13 1
a 5 14 1
a 13 14 1
a 16 15 1
a 15 16 1
a 18 17 1
a 17 18 1
a 20 19 1
a 19 20 1
a 22 21 1
a 21 22 1
a 24 23 1
a 23 24 1
a 25 24 1
a 24 25 1
a 27 26 1
a 26 27 1
a 28 27 1
a 27 28 1
a 29 28 1
a 28 29 1
```

Could you let me know if there is something wrong with this format? Also, from the code you have referenced, it looks like it expects the first byte of the input file to be '1', which it clearly is not in the example shown above. Could you mention what is the expected .gr format (how such a file looks like)?

Thanks!

**Comment by tbennun** [comment]
OK, that explains it! The .gr format we use is a binary gr file format. A converter can be found bundled with Galois: https://github.com/IntelligentSoftwareSystems/Galois/tree/master/tools/graph-convert

**Comment by the-humble-programmer** [comment]
Oh! Thank you. Is there a way to make it work with .mtx file itself directly? When I try running it on a .mtx with this command:

./cc --graphfile=example.mtx --ggr=false

I get the following error:

Cannot read this type of file format [fmt=                         1638180]!

I noticed that it has taken the format of .mtx differently again (once again, is it a binary .mtx file?). It checks if the fmt is less than 111. But according to the .mtx file format, the third field of the header line (which is taken as fmt here by groute) indicates the number of edges. So every time the number of edges is more than 111, it throws this error. If it's less than 111, it runs, but doesn't give the right output. Again I probably suspect that .mtx format is used differently than the one I have used.

**Comment by tbennun** [comment]
Makes sense, the ascii format we use is the METIS file format rather than Matrix Market.

**Comment by the-humble-programmer** [comment]
Ok, that's why it was giving weird results! Thank you for the clarification! :)

**Comment by the-humble-programmer** [comment]
I just went through the METIS file format, and wondered how a node with no neighbours is represented? The format says that a graph of N nodes should have N+1 lines in the file, where each line indicates the neighbours. But if a node has no neighbours, do we have a blank line, or is something else filled in that line?

**Comment by tbennun** [comment]
I wouldn't know, but according to what I understand from the code an empty line would do. 
You can also use the converter mentioned above to be sure.

**Comment by the-humble-programmer** [comment]
Just managed to figure it out -- yes, you are right, an empty line would do. For some reason, Galois was giving cmake errors, so I decided to implement the converter myself :D Thanks for your help!
