### ISSUE TITLE
Why unknown error (30) happened frequently when modify the source code

### ISSUE THREAD

**Issue by pwrliang** [groute/groute#7]
I tried to do a little modification to the code such as add a "printf" statement. When I compile & run the PageRank example, an exception happened.

`Loading graph /mnt/sda2/data/ppopp17-artifact/soc-LiveJournal1/soc-LiveJournal1-weighted-1.gr (1)
/mnt/sda2/liang/ppopp17-artifact/soc-LiveJournal1/soc-LiveJournal1-weighted-1.gr has 4847571 nodes and 68993773 edges
read 68993773 edges

read data for 68993773 edges
----- Running PR -----

ERROR in /home/liang/groute/include/groute/event_pool.h:308: unknown error (30)
`
  The unknown error happened frequently. Sometimes, just call cudaMalloc will cause "unknown error (30)". But When I just clean and make again, the problem vanishes, but sometimes this will not work. I need to remove my modifications and recompile, and add the modifications and compile. It's strange and annoying. I know you may already graduate. But I just need a hint I will appreciate. Thank you.

**Comment by tbennun** [comment]
I don't think this has anything to do with Groute. Error code 30 is an internal error code, as can also be seen in this forum discussion:
https://devtalk.nvidia.com/default/topic/981647/cuda-unknown-error-code-error-30-/
